spring.application.name=salesdashboard
spring.datasource.url=jdbc:mysql://localhost:3306/salesdashboard
spring.datasource.username=root
spring.datasource.password=Harshini@33661328

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true